name: Report

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  watch:
    types: [started]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    if: github.repository == '0123-smallbottle/loudflare-WAF-to-AbuseIPDB'
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/HongKong
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}  # Comma-separated Zone IDs
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
      WHITELISTED_IPS: ${{ secrets.WHITELISTED_IPS }}  # Comma-separated whitelisted IPs
    
    steps:
      - name: Check required secrets
        run: |
          missing_secrets=()
          [ -z "$CLOUDFLARE_ZONE_ID" ] && missing_secrets+=("CLOUDFLARE_ZONE_ID")
          [ -z "$CLOUDFLARE_EMAIL" ] && missing_secrets+=("CLOUDFLARE_EMAIL")
          [ -z "$CLOUDFLARE_API_KEY" ] && missing_secrets+=("CLOUDFLARE_API_KEY")
          [ -z "$ABUSEIPDB_API_KEY" ] && missing_secrets+=("ABUSEIPDB_API_KEY")
          [ -z "$WHITELISTED_IPS" ] && missing_secrets+=("WHITELISTED_IPS")
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "Error: Missing required secrets: ${missing_secrets[*]}"
            echo "Please add these secrets in your repository settings"
            exit 1
          fi
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run report script
        run: |
          python main.py "$CLOUDFLARE_ZONE_ID" "$CLOUDFLARE_EMAIL" "$CLOUDFLARE_API_KEY" "$ABUSEIPDB_API_KEY" "$WHITELISTED_IPS"
