name: Report

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  push:
    branches:
      - main  # or your default branch
  watch:
    types: [started]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    if: github.repository == '0123-smallbottle/loudflare-WAF-to-AbuseIPDB'
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/HongKong
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run report script
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
        run: |
          python main.py "$CLOUDFLARE_ZONE_ID" "$CLOUDFLARE_EMAIL" "$CLOUDFLARE_API_KEY" "$ABUSEIPDB_API_KEY"
